# CI - Build and test dotnet project
name: build_project

on:
  push:
    branches: [production, development]
  pull_request:
    branches: [production, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: |
          dotnet restore api
          dotnet restore api.Tests

      - name: Build
        run: |
          dotnet build --no-restore api
          dotnet build --no-restore api.Tests

      - name: Test
        run: cd api.Tests && dotnet test --no-build --verbosity normal
